# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Barajeel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Barajeel

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  target 'Barajeel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

    pod 'RNAudio', :path => '../node_modules/react-native-audio'

    pod 'RNSound', :path => '../node_modules/react-native-sound'

  end

  target 'BarajeelTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Barajeel-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Barajeel-tvOS

  # target 'Barajeel-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
