# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trust' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trust

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'


  target 'Trust-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  end

  target 'TrustTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Trust-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Trust-tvOS

  # target 'Trust-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
