import LocalizedStrings from "react-native-localization";
export default (localization = new LocalizedStrings({
  en: {
    home: "home",
    profile: "profile",

    main: "main",
    request: "request",
    selectYourRequestSpeed: "select your request speed",
    speedWithin4Housrs: "urgent (within 4 hours + 4 Real Omani)",
    ordinaryWithIn7hHours: "ordinary (within 7 hours)",
    chooseYourAppoinment: "choose your appointment",
    morningFrom8to12: "morning (from 8 am to 12 pm)",
    eveningfrom12to6: "eveing (from 12 pm to 6 pm)",
    email: "email",
    password: "password",
    remeberMe: "remember me",
    didYouForgetPassword: "did you forget your password",
    login: "login",
    donotHaveAccout: "dont't have account?",
    register: "register",
    userName: "user name",
    phoneNumber: "phone number",
    explainYourProblem: "explain your problem",
    recordYourNotes: "record your notes",
    attacImage: "attach an image",
    writeNotes: "write notes",
    myOrders: "my orders",
    RequestPending: "pending ",
    RequestDone: "Done",
    newRequest: "new",
    requestNumber: "request number",
    service: "service",
    requestDate: "request date",
    requestSpeed: "request speed",
    address: "address",
    aboutUs: "about us",
    generalInfo: "general info",
    changePassword: "change password",
    changeLanguage: "change language",
    logOut: "log out",
    areYouSureOfProccessingTheRequest:
      "are you sure of proccessing the request",
    confirm: "confirm",
    close: "close",
    next: "next",
    yourLocation: "your location"
  },
  ar: {
    home: "الرئسيه",
    profile: "الشخصيه",
    main: "الرئيسية",
    request: "طلب",
    selectYourRequestSpeed: "اختار سرعة طلبك",
    speedWithin4Housrs: "(عاجل (خلال 4 ساعات + 4 ريال",
    ordinaryWithIn7hHours: "(عادى (خلال 7 ساعات ",
    chooseYourAppoinment: "حدد الموعد",
    morningFrom8to12: "(صباحا (من 8 صباحا حتى 12 مساء",
    eveningfrom12to6: "(مساء من (12 مساء الى 6 مساء",
    email: "البريد الاليكترونى",
    password: "كلمه المرور",
    remeberMe: "تذكرنى",
    didYouForgetPassword: "هل نسيت كلمه المرور",
    login: "دخول",
    donotHaveAccout: "لاتمتلك حساب؟",
    register: "تسجيل",
    userName: "اسم المستخدم",

    phoneNumber: "رقم الجوال",
    explainYourProblem: "توضيح مشكلتك",
    recordYourNotes: "سجل ملاحظاتك",
    attacImage: "ارفاق صوره",
    writeNotes: "اكتب ملاحظه",
    myOrders: "طلباتى",
    RequestPending: "قيد التنقيذ ",
    RequestDone: "تم التنفيذ",
    newRequest: "جديد",
    requestNumber: "رقم الطلب",
    service: "الخدمه",
    requestDate: "تاريخ الطلب",
    requestSpeed: "سرعه الطلب",
    address: "العنوان",
    aboutUs: "عنا",
    generalInfo: "معلومات عامه",
    changePassword: "تغير كلمه السر",
    changeLanguage: "تغير اللغه",
    logOut: "تسجيل خروج",
    areYouSureOfProccessingTheRequest: "هل انت متاكد من مواصله طلبم",
    confirm: "تاكيد",
    close: "اغلاق",
    next: "التالى",
    yourLocation: "موقعك"
  }
}));
